import { useRef, useState, type ReactNode } from 'react';
import { ArrowRight, Bookmark, CheckCheck, Download, Heart, Pencil, Plus, ShoppingBasket, Trash2, Upload, X } from 'lucide-react';
import { asset, recipes, type Recipe } from './data';
import { formatAmount } from './lib';
import { backupJSON, groupShopping, parseBackup, type JournalEntry, type Notebook } from './notebook';
import { JournalForm, type UpdateNotebook } from './Journal';

function Shopping({ notebook, update, notify }: { notebook: Notebook; update: UpdateNotebook; notify: (message: string) => void }) {
  const [name, setName] = useState('');
  const [amount, setAmount] = useState('1');
  const [unit, setUnit] = useState('個');
  const [copyText, setCopyText] = useState('');
  const groups = groupShopping(notebook.shopping);
  return <section className="shopping-panel"><div className="shopping-toolbar"><p>同じ食材・単位でまとめています。</p><button className="text-button" disabled={!notebook.shopping.some(item => item.checked)} onClick={() => update(value => ({ ...value, shopping: value.shopping.filter(item => !item.checked) }))}><CheckCheck size={16}/>チェック済みを削除</button></div>
    {!groups.length && <div className="shopping-empty"><ShoppingBasket size={30}/><p>レシピから材料を追加するか、下の欄に買い足すものをどうぞ。</p></div>}
    {groups.map(group => <div className="shopping-aggregate" key={group.key}><div className={`shopping-item ${group.checked ? 'checked' : ''}`}><label><input type="checkbox" checked={group.checked} aria-label={`${group.name}を購入済みにする`} onChange={() => update(value => ({ ...value, shopping: value.shopping.map(item => group.items.some(source => source.id === item.id) ? { ...item, checked: !group.checked } : item) }))}/><span>{group.name}</span><span className="shopping-amount">{formatAmount(group.amount)} {group.unit}</span></label><button className="icon-button" aria-label={`${group.name}を買い物リストから削除`} onClick={() => update(value => ({ ...value, shopping: value.shopping.filter(item => !group.items.some(source => source.id === item.id)) }))}><X size={16}/></button></div><details><summary>{group.items.length}件の内訳{group.items.some(item => item.checked) && !group.checked ? '・一部購入済み' : ''}</summary>{group.items.map(item => <p key={item.id}>{recipes.find(recipe => recipe.id === item.recipeId)?.title.replace('\n', '') ?? '自分で追加'}<span>{formatAmount(item.amount)} {item.unit}{item.checked ? '（購入済み）' : ''}</span></p>)}</details></div>)}
    <form className="shopping-add" onSubmit={event => { event.preventDefault(); if (!name.trim() || !Number.isFinite(Number(amount)) || Number(amount) <= 0 || Number(amount) > 100000) return; update(value => ({ ...value, shopping: [...value.shopping, { id: crypto.randomUUID(), recipeId: 'custom', name: name.trim(), amount: Number(amount), unit: unit.trim(), checked: false }] })); setName(''); notify('買い足すものを追加しました'); }}><h3>買い足すもの</h3><div><input aria-label="買い足すもの" placeholder="例：お茶" maxLength={100} required value={name} onChange={event => setName(event.target.value)}/><input aria-label="買い足す数量" type="number" min="0.01" max="100000" step="0.01" required value={amount} onChange={event => setAmount(event.target.value)}/><input aria-label="買い足す単位" maxLength={40} value={unit} onChange={event => setUnit(event.target.value)}/><button className="button" type="submit"><Plus size={16}/>追加</button></div></form>
    <button className="button button-outline full-width" disabled={!notebook.shopping.some(item => !item.checked)} onClick={async () => { const text = groupShopping(notebook.shopping.filter(item => !item.checked)).map(group => `□ ${group.name} ${formatAmount(group.amount)} ${group.unit}`).join('\n'); try { await navigator.clipboard.writeText(text); notify('未購入の買い物リストをコピーしました'); } catch { setCopyText(text); } }}>未購入リストをコピー</button>{copyText && <label className="copy-fallback">長押しで選択してコピーできます<textarea aria-label="コピー用の買い物リスト" readOnly value={copyText} onFocus={event => event.target.select()}/></label>}
  </section>;
}

function Backup({ notebook, update, notify }: { notebook: Notebook; update: UpdateNotebook; notify: (message: string) => void }) {
  const [pending, setPending] = useState<Notebook | null>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  return <section className="backup-panel"><div><span className="eyebrow">KEEP YOUR MEMORIES</span><h2>手帖を、手元に残す。</h2><p>機種変更の前にファイルへ保存。メモ・記録・買い物・調理途中・タイマー・献立・学習記録をまとめて持ち出せます。</p></div><div className="backup-actions"><button className="button button-outline" onClick={() => { const url = URL.createObjectURL(new Blob([backupJSON(notebook)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `kinozen-notebook-${new Date().toISOString().slice(0, 10)}.json`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 10000); notify('手帖のバックアップを書き出しました'); }}><Download size={17}/>手帖を書き出す</button><button className="button button-outline" disabled={busy} onClick={() => fileInput.current?.click()}><Upload size={17}/>{busy ? '読み込み中…' : 'ファイルから復元'}</button><input ref={fileInput} type="file" accept=".json,application/json" aria-label="手帖のバックアップファイル" hidden onChange={async event => { const file = event.target.files?.[0]; event.target.value = ''; setPending(null); setError(''); if (!file) return; setBusy(true); try { if (file.size > 2 * 1024 * 1024) throw new Error('2MB以内のファイルを選んでください。'); setPending(parseBackup(await file.text())); } catch (error) { setError(error instanceof Error ? error.message : 'ファイルを読み込めませんでした。'); } finally { setBusy(false); } }}/></div>{error && <p className="form-error" role="alert">{error}</p>}{pending && <div className="restore-confirm" role="region" aria-label="復元内容の確認"><h3>この手帖に置き換えますか？</h3><p>献立 {pending.meals.length}件・学習 {Object.keys(pending.learning).length}件・お気に入り {pending.saved.length}件・つくった記録 {pending.cooked.length}件・メモ {Object.keys(pending.notes).length}件・買い物 {pending.shopping.length}件・調理途中 {Object.keys(pending.drafts).length}件・タイマー {pending.timer ? 'あり' : 'なし'}</p><p>現在の手帖は上書きされます。必要なら先に書き出してください。端末間の自動同期は行いません。</p><div className="form-actions"><button className="button button-outline" onClick={() => setPending(null)}>復元をキャンセル</button><button className="button" onClick={() => { update(() => pending); setPending(null); notify('手帖を復元しました'); }}>この内容で置き換えて復元</button></div></div>}<p className="small-note">ファイルには入力したメモや感想が含まれます。大切に保管してください。</p></section>;
}

export function NotebookPage({ notebook, update, recipeCard, onOpen, onSearch, onReset, notify }: { notebook: Notebook; update: UpdateNotebook; recipeCard: (recipe: Recipe) => ReactNode; onOpen: (recipe: Recipe) => void; onSearch: () => void; onReset: () => void; notify: (message: string) => void }) {
  const [tab, setTab] = useState('保存したレシピ');
  const [editor, setEditor] = useState<JournalEntry | 'new' | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [month, setMonth] = useState('すべて');
  const [onlyAgain, setOnlyAgain] = useState(false);
  const months = [...new Set(notebook.cooked.map(item => item.date.slice(0, 7)))].sort().reverse();
  const activeMonth = months.includes(month) ? month : 'すべて';
  const entries = [...notebook.cooked].filter(item => (activeMonth === 'すべて' || item.date.startsWith(activeMonth)) && (!onlyAgain || item.again)).sort((a, b) => b.date.localeCompare(a.date));
  const counts = recipes.map(recipe => ({ recipe, count: notebook.cooked.filter(item => item.recipeId === recipe.id).length })).filter(item => item.count > 0).sort((a,b) => b.count-a.count).slice(0,3);
  const untried = recipes.filter(recipe => notebook.saved.includes(recipe.id) && !notebook.cooked.some(item => item.recipeId === recipe.id));
  return <div className="page-enter notebook-expanded"><div className="page-heading"><span className="eyebrow">YOUR LITTLE COLLECTION</span><h1>わたしの、食卓手帖。</h1><p>つくるたびに、わたしの味になっていく。</p></div><div className="notebook-summary"><div><span>つくった記録</span><strong>{notebook.cooked.length}<small>皿</small></strong></div><div><span>お気に入り</span><strong>{notebook.saved.length}<small>品</small></strong></div><div><span>またつくりたい</span><strong>{notebook.cooked.filter(item => item.again).length}<small>件</small></strong></div></div>
    <div className="tabs" role="tablist" aria-label="手帖の種類">{['保存したレシピ','買い物リスト','つくった記録','振り返り'].map(item => <button role="tab" aria-selected={tab === item} key={item} className={tab === item ? 'selected' : ''} onClick={() => { setTab(item); setEditor(null); }}>{item}</button>)}</div>
    {tab === '保存したレシピ' && <>{notebook.saved.length ? <div className="recipe-grid">{recipes.filter(recipe => notebook.saved.includes(recipe.id)).map(recipeCard)}</div> : <div className="empty-state"><Bookmark size={36}/><h2>お気に入りを、ひとつから。</h2><p>レシピのしおりマークから保存できます。</p><button className="button" onClick={onSearch}>レシピを見つける<ArrowRight size={16}/></button></div>}{Object.keys(notebook.notes).length > 0 && <section className="memo-library"><h2>次のわたしへのメモ</h2>{recipes.filter(recipe => notebook.notes[recipe.id]).map(recipe => <button key={recipe.id} className="memo-card" onClick={() => onOpen(recipe)}><Pencil size={18}/><div><h3>{recipe.title.replace('\n','')}</h3><p>{notebook.notes[recipe.id]}</p><span>レシピを開いて編集 →</span></div></button>)}</section>}</>}
    {tab === '買い物リスト' && <Shopping notebook={notebook} update={update} notify={notify}/>}
    {tab === 'つくった記録' && <><div className="journal-toolbar"><label>月で見る<select aria-label="記録の月" value={activeMonth} onChange={event => setMonth(event.target.value)}><option>すべて</option>{months.map(item => <option key={item}>{item}</option>)}</select></label><label className="again-check"><input type="checkbox" checked={onlyAgain} onChange={event => setOnlyAgain(event.target.checked)}/>またつくりたい</label><button className="button" onClick={() => setEditor('new')}><Plus size={17}/>記録を追加</button></div>{editor && <JournalForm key={editor === 'new' ? 'new' : editor.id} notebook={notebook} update={update} entry={editor === 'new' ? undefined : editor} onCancel={() => setEditor(null)} onDone={() => { setEditor(null); setMonth('すべて'); setOnlyAgain(false); notify('つくった記録を保存しました'); }}/>}<div className="cooked-list journal-timeline">{entries.map((entry,index) => { const recipe = recipes.find(item => item.id === entry.recipeId)!; return <div key={entry.id}>{(index === 0 || entries[index-1].date.slice(0,7) !== entry.date.slice(0,7)) && <h2 className="journal-month">{entry.date.slice(0,7).replace('-', '年')}月</h2>}<article><button className="journal-photo" onClick={() => onOpen(recipe)} aria-label={`${recipe.title.replace('\n','')}のレシピを開く`}><img src={asset(recipe.image)} alt=""/></button><div className="journal-entry"><span>{entry.date.replaceAll('-','.')}{entry.again && <Heart size={14} fill="currentColor"/>}</span><button className="journal-title" onClick={() => onOpen(recipe)}><h3>{recipe.title.replace('\n','')}</h3></button>{entry.comment && <p>{entry.comment}</p>}<div className="journal-entry-actions"><button className="text-button" onClick={() => setEditor(entry)}><Pencil size={14}/>記録を編集</button><button className="text-button" aria-label={`${recipe.title.replace('\n','')}の記録を削除`} onClick={() => setDeleting(entry.id)}><Trash2 size={14}/>削除</button></div>{deleting === entry.id && <div className="delete-confirm"><p>この日の記録を削除しますか？</p><button className="text-button" onClick={() => setDeleting(null)}>残す</button><button className="text-button" onClick={() => { update(value => ({ ...value, cooked: value.cooked.filter(item => item.id !== entry.id) })); setDeleting(null); notify('記録を削除しました'); }}>この記録を削除</button></div>}</div></article></div>; })}</div>{!entries.length && <div className="empty-state"><h2>{notebook.cooked.length ? 'この条件の記録はありません。' : '今日のひと皿が、思い出に。'}</h2><p>「記録を追加」から、つくった日と感想を残せます。</p></div>}</>}
    {tab === '振り返り' && <div className="reflection"><section><span className="eyebrow">YOUR TABLE, AGAIN</span><h2>わたしの定番。</h2><p>よくつくる料理を、もう一度。</p>{counts.length ? <div className="reflection-favorites">{counts.map(({ recipe,count }) => <button key={recipe.id} onClick={() => onOpen(recipe)}><img src={asset(recipe.image)} alt=""/><div><span>{count}回、食卓に。</span><h3>{recipe.title.replace('\n','')}</h3></div><ArrowRight size={16}/></button>)}</div> : <p className="empty-inline">つくった記録が増えると、ここに定番の料理が並びます。</p>}</section><section><h2>次につくってみたい。</h2><p>保存した料理のうち、まだ記録のないもの。</p>{untried.length ? <div className="recipe-grid">{untried.map(recipeCard)}</div> : <button className="button button-outline" onClick={onSearch}>新しいひと皿を探す<ArrowRight size={16}/></button>}</section></div>}
    <Backup notebook={notebook} update={update} notify={notify}/><div className="notebook-privacy"><p><Heart size={14}/>手帖はこのブラウザに保存されます。</p><button className="text-button" onClick={onReset}>手帖のデータを削除</button></div>
  </div>;
}

export function PersonalTable({ notebook, onOpen }: { notebook: Notebook; onOpen: (recipe: Recipe) => void }) {
  const drafts = Object.entries(notebook.drafts).filter(([id, draft]) => draft.finished.length < (recipes.find(recipe => recipe.id === id)?.steps.length ?? 0)).sort((a,b) => b[1].updatedAt-a[1].updatedAt);
  const recent = [...notebook.cooked].sort((a,b) => b.date.localeCompare(a.date)).map(item => item.recipeId);
  const ids = [...new Set([...drafts.map(([id]) => id), ...recent, ...notebook.saved])].slice(0,3);
  if (!ids.length) return null;
  return <section className="personal-table"><div className="section-heading"><div><span className="eyebrow">BACK TO YOUR TABLE</span><h2>わたしの食卓の、続きから。</h2></div></div><div className="personal-table-grid">{ids.map(id => { const recipe = recipes.find(item => item.id === id)!; const draft = drafts.find(([key]) => key === id)?.[1]; return <button key={id} onClick={() => onOpen(recipe)}><img src={asset(recipe.image)} alt=""/><div><span>{draft ? `つくりかけ · ${draft.finished.length}/${recipe.steps.length}工程` : recent.includes(id) ? '最近つくった料理' : '保存した料理'}</span><h3>{recipe.title.replace('\n','')}</h3><small>{draft ? '続きへ' : 'レシピへ'} →</small></div></button>; })}</div></section>;
}
