import { useState } from 'react';
import { recipes, asset, type Recipe } from './data';
import { addIngredients, type Notebook } from './notebook';
import { todayISO } from './lib';
export type Update = (fn:(n:Notebook)=>Notebook)=>void;
export const roles=['主食','主菜','副菜','汁物'] as const;
export function recipeRole(r:Recipe){return r.tags.includes('主菜')?'主菜':r.category==='ごはん'?'主食':r.category==='汁もの'?'汁物':'副菜';}
export const pantryName=(name:string)=>name.replace(/[（(].*?[）)]/g,'').replace(/木綿|絹ごし/,'').trim();
const staples=new Set(['水','塩','砂糖','しょうゆ','みりん','油','オリーブ油','ごま油','酒','酢','片栗粉','だし汁','味噌']);
export function pantryMatch(recipe:Recipe, selected:string[]){const main=recipe.ingredients.filter(i=>!staples.has(pantryName(i.name)));return {matched:main.filter(i=>selected.includes(pantryName(i.name))),missing:main.filter(i=>!selected.includes(pantryName(i.name)))};}
export function Planner({notebook,update,onOpen,notify}:{notebook:Notebook;update:Update;onOpen:(r:Recipe)=>void;notify:(s:string)=>void}){
 const [chosen,setChosen]=useState<string[]>([]),[servings,setServings]=useState(2),[name,setName]=useState('今日の献立'),[edit,setEdit]=useState<string|null>(null);
 const selected=recipes.filter(r=>chosen.includes(r.id));
 return <section className="rich-panel"><span className="eyebrow">献立を組む</span><h2>今日の食卓を、組み立てる。</h2><p>ひと皿だけでも。役割ごとに選んで、食卓全体を眺めましょう。</p><div className="meal-slots">{roles.map(role=><label key={role}>{role}<select aria-label={`${role}を選ぶ`} value={selected.find(r=>recipeRole(r)===role)?.id??''} onChange={e=>setChosen(v=>[...v.filter(id=>recipeRole(recipes.find(r=>r.id===id)!)!==role),...(e.target.value?[e.target.value]:[])])}><option value="">選ばない</option>{recipes.filter(r=>r.category!=='甘いもの'&&recipeRole(r)===role).map(r=><option key={r.id} value={r.id}>{r.title.replace('\n','')}</option>)}</select></label>)}</div><div className="mini-dishes">{selected.map(r=><button key={r.id} onClick={()=>onOpen(r)}><img src={asset(r.image)} alt=""/>{r.title.replace('\n','')}</button>)}</div><div className="rich-fields"><label>献立の名前<input aria-label="献立の名前" maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>人数<select aria-label="献立の人数" value={servings} onChange={e=>setServings(+e.target.value)}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}人分</option>)}</select></label></div><div className="form-actions"><button className="button" disabled={!chosen.length||!name.trim()} onClick={()=>{update(n=>({...n,meals:[...n.meals.filter(m=>m.id!==edit),{id:edit??crypto.randomUUID(),name:name.trim(),recipeIds:chosen,servings}]}));setEdit(null);notify('献立を保存しました');}}>献立を保存</button><button className="button button-outline" disabled={!chosen.length} onClick={()=>{update(n=>({...n,shopping:selected.reduce((items,r)=>addIngredients(items,r,servings),n.shopping)}));notify(`${servings}人分の献立を買い物リストに追加しました`);}}>献立の材料を買い物へ</button></div><p className="small-note">同じ料理の材料は人数分で更新します。調味料も含みます。栄養量や個別の食事制限を判定する機能ではありません。</p><h3>保存した献立</h3>{!notebook.meals.length&&<p>気に入った組み合わせを残しましょう。</p>}{notebook.meals.map(m=><div className="saved-meal" key={m.id}><strong>{m.name} · {m.servings}人分</strong><p>{m.recipeIds.map(id=>recipes.find(r=>r.id===id)?.title.replace('\n','')).join(' / ')}</p><button className="text-button" onClick={()=>{setChosen(m.recipeIds);setName(m.name);setServings(m.servings);setEdit(m.id);}}>この献立を使う・編集</button><button className="text-button" onClick={()=>{update(n=>({...n,meals:n.meals.filter(x=>x.id!==m.id)}));if(edit===m.id)setEdit(null);}}>献立を削除</button></div>)}</section>;
}
export function Pantry({onOpen}:{onOpen:(r:Recipe)=>void}){const [selected,setSelected]=useState<string[]>([]);const names=[...new Set(recipes.flatMap(r=>r.ingredients.map(i=>pantryName(i.name))))].filter(n=>!staples.has(n));const matches=recipes.map(r=>({r,...pantryMatch(r,selected)})).filter(x=>x.matched.length).sort((a,b)=>a.missing.length-b.missing.length||b.matched.length-a.matched.length);return <section className="rich-panel"><h2>家にある食材から</h2><p>複数選ぶと、足りない主な材料が少ない順に並びます。量はレシピで確認してください。</p><div className="chip-row">{names.map(n=><button key={n} className={`chip ${selected.includes(n)?'selected':''}`} aria-pressed={selected.includes(n)} onClick={()=>setSelected(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n])}>{n}</button>)}</div>{!!selected.length&&<button className="text-button" onClick={()=>setSelected([])}>食材の選択をクリア</button>}<p className="small-note">水・塩・しょうゆ・油などの基本調味料は照合から除外しています。アレルギー対応の判定はしません。</p><div className="pantry-results">{matches.map(({r,matched,missing})=><article key={r.id}><button className="text-button" onClick={()=>onOpen(r)}>{r.title.replace('\n','')}</button><p>使える：{matched.map(i=>i.name).join('・')}</p><small>{missing.length?'あと：'+missing.map(i=>i.name).join('・'):'主な材料がそろっています'}</small></article>)}</div></section>}
const features=[{season:'春',title:'春の緑を、ひと皿に。',text:'豆の粒、葉野菜の緑。火を入れる順番を変えて、それぞれの食感を楽しみましょう。',foods:['ほうれん草','キャベツ'],ids:['pea-rice','pork-cabbage','spinach-tofu']},{season:'夏',title:'夏の彩りと、酸味。',text:'トマトの酸味やとうもろこしの甘みを食卓へ。暑さだけで食べ方を決めず、好みの温度で。',foods:['トマト','なす'],ids:['corn-rice','mackerel-tomato','eggplant-ginger']},{season:'秋',title:'秋の香りを、炊き込む。',text:'きのこの香り、いもの甘み。炊飯器にまかせる主食と、おかずを組み合わせる特集です。',foods:['しめじ','さつまいも'],ids:['mushroom-rice','salmon-steam','sweet-rice']},{season:'冬',title:'冬の鍋から、湯気のごちそう。',text:'根菜は厚さで火の通りが変わります。煮ものと汁もので、やわらかさの違いを楽しんで。',foods:['れんこん','にんじん'],ids:['chicken-daikon','lotus-soup','carrot-sesame']}];
export function SeasonalFeatures({onOpen,onFood,onLearn}:{onOpen:(r:Recipe)=>void;onFood:(name:string)=>void;onLearn:()=>void}){return <section className="rich-panel"><span className="eyebrow">四季の読みもの</span><h2>季節を味わう、四つの特集</h2><div className="feature-grid">{features.map(f=><article key={f.season}><img src={asset(recipes.find(r=>r.id===f.ids[0])!.image)} alt=""/><span className="eyebrow">{f.season}の食卓</span><h3>{f.title}</h3><p>{f.text}</p><div className="chip-row">{f.foods.map(n=><button className="chip" key={n} onClick={()=>onFood(n)}>{n}を知る</button>)}</div>{f.ids.map(id=><button className="text-button feature-recipe" key={id} onClick={()=>onOpen(recipes.find(r=>r.id===id)!)}>{recipes.find(r=>r.id===id)!.title.replace('\n','')} →</button>)}</article>)}</div><button className="button button-outline" onClick={onLearn}>季節と食養生を学ぶ</button></section>}
export function JournalCalendar({notebook,update,onOpen,notify}:{notebook:Notebook;update:Update;onOpen:(r:Recipe)=>void;notify:(s:string)=>void}){const [month,setMonth]=useState(todayISO().slice(0,7)),[day,setDay]=useState('');const [y,m]=month.split('-').map(Number);const count=new Date(y,m,0).getDate(),start=new Date(y,m-1,1).getDay();const entries=notebook.cooked.filter(e=>e.date===day);return <section className="rich-panel"><h2>食卓のカレンダー</h2><label>表示する月<input type="month" aria-label="カレンダーの月" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){setMonth(e.target.value);setDay('');}}}/></label><div className="meal-calendar">{'日月火水木金土'.split('').map(x=><span key={x}>{x}</span>)}{Array.from({length:start},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`;const n=notebook.cooked.filter(e=>e.date===date).length;return <button className={date===day?'selected':''} key={date} aria-label={`${date} ${n}品`} onClick={()=>setDay(date)}>{i+1}<small>{n?`${n}品`:'·'}</small></button>})}</div>{day&&<div aria-live="polite"><h3>{day}の食卓</h3>{!entries.length?<p>この日の記録はありません。</p>:<>{entries.map(e=><button className="text-button feature-recipe" key={e.id} onClick={()=>onOpen(recipes.find(r=>r.id===e.recipeId)!)}>{recipes.find(r=>r.id===e.recipeId)!.title.replace('\n','')}</button>)}<button className="button button-outline" onClick={()=>{update(n=>({...n,meals:[...n.meals,{id:crypto.randomUUID(),name:`${day}の食卓`,recipeIds:entries.map(e=>e.recipeId),servings:2}]}));notify('この日の料理を献立に保存しました。人数は2人分です');}}>この日の料理を献立に保存</button><p className="small-note">調理記録には人数がないため、2人分で保存します。</p></>}</div>}</section>}
